languageCode: "en-us"
title: "Isabella Noble"
baseURL: "https://www.isabellanoble.com/"
publishDir: "docs"
params:
    name: "Isabella Noble"
    description: "CV, Portfolio and Blog"
    navigation:
        brand: "Isabella Noble"
    header:
        image: "in_headshot.png"
        name: "Isabella Noble"
        subtitle: "Travel Journalist"
    portfolio:
        modal:
            client: "Client"
            date: "Date"
            category: "Category"
            buttontext: "Close"
    about:
        title: "About"
        left: "English-Australian on paper but Spanish at heart, London-based travel journalist Isabella has been wandering the globe since her first round-the-world trip as a one-year-old. Having grown up in a whitewashed Andalucian village (picking up a lifelong malagueño accent), she is a bilingual Spain specialist, but also writes extensively about India, Southeast Asia, Greece, the UK and beyond.        "
        right: "Isabella has lived in London, Melbourne and Andalucía, and writes for Lonely Planet, Telegraph Travel, Ink Global and other print and digital media. She also works as a sub-editor, is a Spain expert for Telegraph Travel and has contributed to over 30 Lonely Planet titles, including multiple editions of Spain, Andalucía, India, South India, Thailand, Greece and Great Britain, as well was Pocket Phuket, Pocket Ibiza and Pocket Barcelona.         "
    contact:
        title: "Get In Touch"
        form:
            name:
                text: "Name"
                error: "Please enter your name"
            email:
                text: "Email Address"
                error: "Please enter your email address"
            message:
                text: "Message"
                error: "Please enter a message"
            button:
                text: "Send"
    footer:
        copyright: "© Isabella Noble 2020"
    social:
        networks:
            - icon: "fa-instagram"
              link: "//instagram.com/isabellamnoble"
            - icon: "fa-twitter"
              link: "//twitter.com/isabellamnoble"
            - icon: "fa-linkedin"
              link: "//linkedin.com/in/isabella-noble-89233631"
                
